language: node_js
node_js: "12.16.1"
cache: npm
before_install:
install:
  - npm ci
before_script:
  - export NODE_OPTIONS=–max_old_space_size=4096
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
